Fix/headings in tables
puzzle/prawn-markup pull request #60
Opened 2024-12-22 14:56 UTC by diegosteiner

When the markup contains a table with a nested heading inside, the current behavior will pass on all options of the heading to the cell, which can lead to an error like this:

```rb
undefined method `style=' for an instance of Prawn::Table::Cell::Text
```

Proposal: only pass on known options to prawn-table

2025-01-07 08:58 UTC, codez requested changes
Thanks for the pull request, this looks good. Please check the action results for remaining issues.

2025-01-07 08:58 UTC, codez commented on lib/prawn/markup/processor/tables.rb
> +                           overflow rotate rotate_around single_line size text_color valign])
The options hash must not be modified in this method. Use `options = options.slice(...)` to create a new object. Furthermore, `slice!` is not in the ruby stdlib anyways.

2025-01-08 09:04 UTC, diegosteiner commented
I've fixed the specs and linting and changed to code as requested. 

I'd be glad if you could look into the specs, I was unable to figure out why the top_positions of the nested headings are where are now.

2025-01-08 09:05 UTC, diegosteiner commented on spec/prawn/markup/processor/tables_spec.rb
> +      expect(top_positions).to eq([first_row_top - 17, first_row_top - 50].map(&:round))
Why do the headings start at offset 17 and (36 + 14)?

2025-01-08 14:18 UTC, codez commented on spec/prawn/markup/processor/tables_spec.rb
> +      expect(top_positions).to eq([first_row_top - 17, first_row_top - 50].map(&:round))
Heading top positions are indeed complex, even in the headings specs we use the "magic" values. I'm fine with these hard-coded values here.

2025-01-08 14:20 UTC, merged

2025-02-19 14:16 UTC, codez commented
@diegosteiner FYI, I just released a new version of prawn-markup with these changes